const employees = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@company.com",
    password: "password",
    tasks: [
      {
        title: "Task 1",
        description: "Prepare an annual financial report for upcoming board review.",
        date: "2024-10-25",
        category: "Documentation",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Implement API integration for real-time data updates on dashboard.",
        date: "2024-10-23",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Coordinate with civil engineers to finalize project timelines.",
        date: "2024-10-26",
        category: "Meetings",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Conduct security review to ensure compliance with regulations.",
        date: "2024-10-28",
        category: "Security",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5",
        description: "Draft a report on system performance for IT audit purposes.",
        date: "2024-10-30",
        category: "Analysis",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@company.com",
    password: "password",
    tasks: [
      {
        title: "Task 1",
        description: "Redesign the main landing page with a user-friendly interface.",
        date: "2024-10-21",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Write test cases to validate new features in the finance module.",
        date: "2024-10-23",
        category: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Update database indexing to improve query performance.",
        date: "2024-10-27",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Attend a project meeting to discuss civil site requirements.",
        date: "2024-10-28",
        category: "Meetings",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5",
        description: "Conduct data integrity checks for all archived reports.",
        date: "2024-10-29",
        category: "Quality Control",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    name: "Charlie Davis",
    email: "charlie.davis@company.com",
    password: "password",
    tasks: [
      {
        title: "Task 1",
        description: "Develop presentation slides for the upcoming product demo.",
        date: "2024-10-28",
        category: "Presentation",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Review project pull requests and ensure code standards are met.",
        date: "2024-10-22",
        category: "Code Review",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Perform regular database backups to secure project data.",
        date: "2024-10-24",
        category: "Maintenance",
        active: true,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Task 4",
        description: "Assist in testing new security protocols for mobile apps.",
        date: "2024-10-29",
        category: "Testing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5",
        description: "Organize code documentation for the IT operations team.",
        date: "2024-10-30",
        category: "Documentation",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    name: "Diana Roberts",
    email: "diana.roberts@company.com",
    password: "password",
    tasks: [
      {
        title: "Task 1",
        description: "Create API documentation for the authentication module.",
        date: "2024-10-29",
        category: "Documentation",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Enhance report generation with caching mechanisms.",
        date: "2024-10-25",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Setup Docker for DevOps and streamline build processes.",
        date: "2024-10-26",
        category: "DevOps",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Attend and report on cybersecurity training seminar.",
        date: "2024-10-27",
        category: "Training",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5",
        description: "Collaborate on civil infrastructure project data analysis.",
        date: "2024-10-30",
        category: "Analysis",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    name: "Evan Lee",
    email: "evan.lee@company.com",
    password: "password",
    tasks: [
      {
        title: "Task 1",
        description: "Plan and organize team retreat for next quarter.",
        date: "2024-10-30",
        category: "Event Planning",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Audit security protocols to enhance data protection measures.",
        date: "2024-10-22",
        category: "Security",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Develop content for the company's weekly newsletter.",
        date: "2024-10-24",
        category: "Communication",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Organize safety protocol documents for civil project compliance.",
        date: "2024-10-25",
        category: "Compliance",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5",
        description: "Analyze team productivity for monthly IT report.",
        date: "2024-10-27",
        category: "Analysis",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 6,
    name: "Frank Martin",
    email: "frank.martin@company.com",
    password: "password",
    tasks: [
      {
        title: "Task 1",
        description: "Update website footer with new compliance guidelines.",
        date: "2024-10-22",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Test cloud infrastructure resilience with load balancing.",
        date: "2024-10-23",
        category: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Coordinate with IT to deploy quarterly updates.",
        date: "2024-10-25",
        category: "Deployment",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Draft new security protocols for data storage.",
        date: "2024-10-26",
        category: "Security",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 7,
    name: "Grace Lee",
    email: "grace.lee@company.com",
    password: "password",
    tasks: [
      {
        title: "Task 1",
        description: "Design mockups for new user onboarding flow.",
        date: "2024-10-20",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Create automated email triggers for user milestones.",
        date: "2024-10-23",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Assist in cross-functional meeting with the marketing team.",
        date: "2024-10-25",
        category: "Meetings",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Oversee mobile app redesign project timelines.",
        date: "2024-10-28",
        category: "Project Management",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5",
        description: "Test new navigation components in the app.",
        date: "2024-10-29",
        category: "Testing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 8,
    name: "Henry Wallace",
    email: "henry.wallace@company.com",
    password: "password",
    tasks: [
      {
        title: "Task 1",
        description: "Research and document competitors' pricing strategies.",
        date: "2024-10-21",
        category: "Analysis",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Implement GDPR compliance updates on the website.",
        date: "2024-10-24",
        category: "Compliance",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Create a presentation on the new data retention policy.",
        date: "2024-10-27",
        category: "Documentation",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Coordinate with HR on policy updates.",
        date: "2024-10-29",
        category: "Meetings",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5",
        description: "Prepare end-of-year review of customer feedback analysis.",
        date: "2024-10-30",
        category: "Analysis",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 9,
    name: "Isla Thompson",
    email: "isla.thompson@company.com",
    password: "password",
    tasks: [
      {
        title: "Task 1",
        description: "Audit and organize data for monthly KPI report.",
        date: "2024-10-20",
        category: "Quality Control",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Enhance mobile app notifications for critical alerts.",
        date: "2024-10-22",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Coordinate team-building activities for department retreat.",
        date: "2024-10-24",
        category: "Event Planning",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Optimize email campaign tracking for better analytics.",
        date: "2024-10-25",
        category: "Marketing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5",
        description: "Test updated analytics on user feedback forms.",
        date: "2024-10-29",
        category: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 10,
    name: "Jake Brown",
    email: "jake.brown@company.com",
    password: "password",
    tasks: [
      {
        title: "Task 1",
        description: "Implement logging for new error reporting module.",
        date: "2024-10-22",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Set up A/B tests for UI changes in main dashboard.",
        date: "2024-10-25",
        category: "Testing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Monitor server health and conduct routine checks.",
        date: "2024-10-26",
        category: "Maintenance",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Finalize content for training manuals for new hires.",
        date: "2024-10-28",
        category: "Documentation",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5",
        description: "Attend strategy meeting with senior developers.",
        date: "2024-10-29",
        category: "Meetings",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 6",
        description: "Create data visualizations for quarterly financial review.",
        date: "2024-10-30",
        category: "Analysis",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
];



  
  const admin = [
    {
      id: 1,
      name : 'Charlie Davis',
      email: "admin@gmail.com",
      password: "admin",
    },
  ];
  
 export  const setLocalStorage= ()=>{
    localStorage.setItem("employees",JSON.stringify(employees));
    localStorage.setItem("admin",JSON.stringify(admin));
 }

 export  const getLocalStorage= ()=>{
  const employee =JSON.parse(localStorage.getItem("employees"));
  const admin =JSON.parse(localStorage.getItem("admin"));
  return {employee,admin};
  
 }
  